apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "ecommerce.fullname" . }}-backend
  labels:
    app: backend

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}


          securityContext:
            runAsNonRoot: {{ .Values.backend.securityContext.runAsNonRoot }}
            allowPrivilegeEscalation: {{ .Values.backend.securityContext.allowPrivilegeEscalation }}
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: {{ .Values.backend.securityContext.seccompProfile.type }}



          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}

            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20

          env:
            - name: ConnectionStrings__Postgres
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: ConnectionStrings__Postgres
