apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret

type: Opaque

data:
  POSTGRES_DB: {{ .Values.postgres.database.name | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.database.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.database.password | b64enc | quote }}

  ConnectionStrings__Postgres: {{ printf "Host=postgres;Port=5432;Database=%s;Username=%s;Password=%s" .Values.postgres.database.name .Values.postgres.database.user .Values.postgres.database.password | b64enc | quote }}